In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import scipy.stats as stats
import env
import wrangle_cluster as wc
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
from sklearn.model_selection import learning_curve

# Exercises

## Sourcing the Zillow database as the data source, create a jupyter notebook named explore_zillow and do the following:

1. Ask at least 5 questions about the data, keeping in mind that your target variable is logerror. e.g. Is logerror significantly different for properties in LA County vs Orange County vs Ventura County?

2. Answer those questions through a mix of statistical tests and visualizations.

In [2]:
df = wc.get_zillow()

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77381 entries, 1727539 to 2455685
Data columns (total 67 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   parcelid                      77381 non-null  int64
 1   airconditioningtypeid         24953 non-null  float64
 2   architecturalstyletypeid      206 non-null    float64
 3   basementsqft                  50 non-null     float64
 4   bathroomcnt                   77381 non-null  float64
 5   bedroomcnt                    77381 non-null  float64
 6   buildingclasstypeid           15 non-null     float64
 7   buildingqualitytypeid         49672 non-null  float64
 8   calculatedbathnbr             76772 non-null  float64
 9   decktypeid                    614 non-null    float64
 10  finishedfloor1squarefeet      6023 non-null   float64
 11  calculatedfinishedsquarefeet  77185 non-null  float64
 12  finishedsquarefeet12          73749 non-null  float64
 13  finishedsquarefeet13          41 non-null     float64
 14  finishedsquarefeet15          3009 non-null   float64
 15  finishedsquarefeet50          6023 non-null   float64
 16  finishedsquarefeet6           386 non-null    float64
 17  fips                          77381 non-null  float64
 18  fireplacecnt                  8276 non-null   float64
 19  fullbathcnt                   76772 non-null  float64
 20  garagecarcnt                  25474 non-null  float64
 21  garagetotalsqft               25474 non-null  float64
 22  hashottuborspa                1538 non-null   float64
 23  heatingorsystemtypeid         49440 non-null  float64
 24  latitude                      77381 non-null  float64
 25  longitude                     77381 non-null  float64
 26  lotsizesquarefeet             69142 non-null  float64
 27  poolcnt                       16137 non-null  float64
 28  poolsizesum                   867 non-null    float64
 29  pooltypeid10                  464 non-null    float64
 30  pooltypeid2                   1074 non-null   float64
 31  pooltypeid7                   15042 non-null  float64
 32  propertycountylandusecode     77381 non-null  object
 33  propertylandusetypeid         77381 non-null  float64
 34  propertyzoningdesc            50331 non-null  object
 35  rawcensustractandblock        77381 non-null  float64
 36  regionidcity                  75910 non-null  float64
 37  regionidcounty                77381 non-null  float64
 38  regionidneighborhood          30890 non-null  float64
 39  regionidzip                   77331 non-null  float64
 40  roomcnt                       77381 non-null  float64
 41  storytypeid                   50 non-null     float64
 42  threequarterbathnbr           10096 non-null  float64
 43  typeconstructiontypeid        222 non-null    float64
 44  unitcnt                       50563 non-null  float64
 45  yardbuildingsqft17            2388 non-null   float64
 46  yardbuildingsqft26            70 non-null     float64
 47  yearbuilt                     77118 non-null  float64
 48  numberofstories               17560 non-null  float64
 49  fireplaceflag                 172 non-null    float64
 50  structuretaxvaluedollarcnt    77269 non-null  float64
 51  taxvaluedollarcnt             77380 non-null  float64
 52  assessmentyear                77381 non-null  float64
 53  landtaxvaluedollarcnt         77379 non-null  float64
 54  taxamount                     77376 non-null  float64
 55  taxdelinquencyflag            2886 non-null   object
 56  taxdelinquencyyear            2886 non-null   float64
 57  censustractandblock           77137 non-null  float64
 58  logerror                      77381 non-null  float64
 59  transactiondate               77381 non-null  object
 60  airconditioningdesc           24953 non-null  object
 61  architecturalstyledesc        206 non-null    object
 62  buildingclassdesc             15 non-null     object
 63  heatingorsystemdesc           49440 non-null  object
 64  propertylandusedesc           77381 non-null  object
 65  storydesc                     50 non-null     object
 66  typeconstructiondesc          222 non-null    object
dtypes: float64(55), int64(1), object(11)
memory usage: 40.1+ MB

In [4]:
wc.wrangle_zillow()

,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedfinishedsquarefeet,fips,latitude,longitude,lotsizesquarefeet,rawcensustractandblock,regionidcity,...,yearbuilt,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,logerror,transactiondate,heatingorsystemdesc,county
0,3.5,4.0,6.0,3100.0,6059.0,33634931.0,-117869207.0,4506.0,6.059063e+07,53571.0,...,1998.0,485713.0,1023282.0,2016.0,537569.0,11013.72,0.025595,2017-01-01,None,Orange
1,1.0,2.0,6.0,1465.0,6111.0,34449266.0,-119281531.0,12647.0,6.111001e+07,13091.0,...,1967.0,88000.0,464000.0,2016.0,376000.0,5672.48,0.055619,2017-01-01,None,Ventura
2,2.0,3.0,6.0,1243.0,6059.0,33886168.0,-117823170.0,8432.0,6.059022e+07,21412.0,...,1962.0,85289.0,564778.0,2016.0,479489.0,6488.30,0.005383,2017-01-01,None,Orange
3,3.0,4.0,8.0,2376.0,6037.0,34245180.0,-118240722.0,13038.0,6.037300e+07,396551.0,...,1970.0,108918.0,145143.0,2016.0,36225.0,1777.51,-0.103410,2017-01-01,Central,Los Angeles
4,3.0,3.0,8.0,1312.0,6037.0,34185120.0,-118414640.0,278581.0,6.037124e+07,12447.0,...,1964.0,73681.0,119407.0,2016.0,45726.0,1533.89,0.006940,2017-01-01,Central,Los Angeles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77376,2.0,2.0,6.0,1286.0,6037.0,34245368.0,-118282383.0,47405.0,6.037101e+07,12447.0,...,1940.0,70917.0,354621.0,2016.0,283704.0,4478.43,0.020615,2017-09-20,Central,Los Angeles
77377,2.0,4.0,6.0,1612.0,6111.0,34300140.0,-118706327.0,12105.0,6.111008e+07,27110.0,...,1964.0,50683.0,67205.0,2016.0,16522.0,1107.48,0.013209,2017-09-21,None,Ventura
77378,1.0,3.0,4.0,1032.0,6037.0,34040895.0,-118038169.0,5074.0,6.037434e+07,36502.0,...,1954.0,32797.0,49546.0,2016.0,16749.0,876.43,0.037129,2017-09-21,Central,Los Angeles
77379,2.0,3.0,6.0,1762.0,6037.0,33937685.0,-117996709.0,6347.0,6.037503e+07,14634.0,...,1955.0,140000.0,522000.0,2016.0,382000.0,6317.15,0.007204,2017-09-25,Central,Los Angeles
77380,2.0,3.0,4.0,1050.0,6037.0,34010864.0,-117900894.0,5927.0,6.037408e+07,118217.0,...,1960.0,77118.0,259334.0,2016.0,182216.0,3345.78,-0.197755,2018-05-25,Floor/Wall,Los Angeles

In [5]:
train, validate, test = wc.train_validate_test_split(df)

In [6]:
df = train

In [7]:
train.head()

,parcelid,airconditioningtypeid,architecturalstyletypeid,basementsqft,bathroomcnt,bedroomcnt,buildingclasstypeid,buildingqualitytypeid,calculatedbathnbr,decktypeid,...,censustractandblock,logerror,transactiondate,airconditioningdesc,architecturalstyledesc,buildingclassdesc,heatingorsystemdesc,propertylandusedesc,storydesc,typeconstructiondesc
id,,,,,,,,,,,,,,,,,,,,,
534463,14362433,NaN,NaN,NaN,2.0,2.0,NaN,NaN,2.0,NaN,...,6.059052e+13,0.007853,2017-06-07,None,None,None,None,Single Family Residential,None,None
1470283,12733749,NaN,NaN,NaN,2.0,3.0,NaN,6.0,2.0,NaN,...,6.037504e+13,0.004492,2017-08-16,None,None,None,Central,Single Family Residential,None,None
1893420,11149006,1.0,NaN,NaN,4.0,5.0,NaN,7.0,4.0,NaN,...,6.037920e+13,0.012171,2017-06-30,Central,None,None,Central,Single Family Residential,None,None
1829705,12964869,1.0,NaN,NaN,2.0,2.0,NaN,8.0,2.0,NaN,...,6.037431e+13,-0.076269,2017-08-29,Central,None,None,Central,Condominium,None,None
492849,17184975,NaN,NaN,NaN,1.0,2.0,NaN,NaN,1.0,NaN,...,6.111005e+13,-0.046222,2017-03-29,None,None,None,None,Condominium,None,None

### What is the distribution of the variables?

In [ ]:
#Univariate exploration, 
for col in train.columns:
    plt.hist(train[col])
    plt.title(col)
    plt.show()

In [ ]:
sns.boxplot(train.bathroomcnt, train.logerror)
plt.title('Bathroom Count and Log Error')
plt.show()